services:
  pyspark:
    image: quay.io/jupyter/pyspark-notebook:latest
    container_name: bges_spark
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    working_dir: /home/jovyan/work
    environment:
      JUPYTER_TOKEN: "bges"
      JUPYTER_ENABLE_LAB: "yes"
      SPARK_OPTS: >-
        --driver-java-options=-Xms512m
        -Dspark.driver.host=localhost
        -Dspark.ui.enabled=false
    restart: unless-stopped
